{
 "title": "Sensors",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All Sensors - Lux",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "query": "SELECT mean(\"lux\") FROM \"mqtt_consumer\"\nWHERE $timeFilter\nGROUP BY time($__interval), \"device_id\" fill(null)"
    }
   ]
  },
  {
   "title": "Garden Sensor 01 - Lux",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "query": "SELECT mean(\"lux\") FROM \"mqtt_consumer\"\nWHERE (\"device_id\" = 'garden_sensor_01') AND $timeFilter\nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Garden Sensor 02 - Lux",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "query": "SELECT mean(\"lux\") FROM \"mqtt_consumer\"\nWHERE (\"device_id\" = 'garden_sensor_02') AND $timeFilter\nGROUP BY time($__interval) fill(null)"
    }
   ]
  }
 ]
}